import { NextRequest, NextResponse } from 'next/server'

// Auto-generated by scripts/update-market-data.mjs
// Source: Redfin Public Market Data (zip_code_market_tracker) — ZIP-level accuracy
// Last updated: 2026-06-19
const MARKET_DATA: Record<string, {
  medianSalePrice: number
  medianDaysOnMarket: number
  activeListings: number | null
  percentAboveList: number
  updatedAt: string
}> = {
  '20190': { medianSalePrice: 600000, medianDaysOnMarket: 30, activeListings: 83, percentAboveList: 0.3333, updatedAt: '2026-06-19' },
  '22041': { medianSalePrice: 438000, medianDaysOnMarket: 36, activeListings: 70, percentAboveList: 0.4328, updatedAt: '2026-06-19' },
  '22042': { medianSalePrice: 727500, medianDaysOnMarket: 23, activeListings: 75, percentAboveList: 0.5446, updatedAt: '2026-06-19' },
  '22043': { medianSalePrice: 950000, medianDaysOnMarket: 26, activeListings: 60, percentAboveList: 0.4416, updatedAt: '2026-06-19' },
  '22044': { medianSalePrice: 850000, medianDaysOnMarket: 24, activeListings: 27, percentAboveList: 0.4815, updatedAt: '2026-06-19' },
  '22046': { medianSalePrice: 1100000, medianDaysOnMarket: 25, activeListings: 46, percentAboveList: 0.4507, updatedAt: '2026-06-19' },
  '22066': { medianSalePrice: 1800000, medianDaysOnMarket: 35, activeListings: 74, percentAboveList: 0.3455, updatedAt: '2026-06-19' },
  '22101': { medianSalePrice: 1957900, medianDaysOnMarket: 29, activeListings: 145, percentAboveList: 0.3361, updatedAt: '2026-06-19' },
  '22102': { medianSalePrice: 522500, medianDaysOnMarket: 31, activeListings: 119, percentAboveList: 0.2841, updatedAt: '2026-06-19' },
  '22180': { medianSalePrice: 1431000, medianDaysOnMarket: 11, activeListings: 56, percentAboveList: 0.4432, updatedAt: '2026-06-19' },
  '22201': { medianSalePrice: 845000, medianDaysOnMarket: 29, activeListings: 88, percentAboveList: 0.3846, updatedAt: '2026-06-19' },
  '22202': { medianSalePrice: 950000, medianDaysOnMarket: 41, activeListings: 52, percentAboveList: 0.3333, updatedAt: '2026-06-19' },
  '22203': { medianSalePrice: 537500, medianDaysOnMarket: 28, activeListings: 39, percentAboveList: 0.3649, updatedAt: '2026-06-19' },
  '22204': { medianSalePrice: 655000, medianDaysOnMarket: 36, activeListings: 116, percentAboveList: 0.3782, updatedAt: '2026-06-19' },
  '22205': { medianSalePrice: 1400000, medianDaysOnMarket: 17, activeListings: 25, percentAboveList: 0.6349, updatedAt: '2026-06-19' },
  '22206': { medianSalePrice: 560000, medianDaysOnMarket: 26, activeListings: 58, percentAboveList: 0.3678, updatedAt: '2026-06-19' },
  '22207': { medianSalePrice: 1533000, medianDaysOnMarket: 20, activeListings: 81, percentAboveList: 0.5556, updatedAt: '2026-06-19' },
  '22209': { medianSalePrice: 740000, medianDaysOnMarket: 57, activeListings: 75, percentAboveList: 0.1633, updatedAt: '2026-06-19' },
  '22213': { medianSalePrice: 1293000, medianDaysOnMarket: 6, activeListings: 11, percentAboveList: 0.5833, updatedAt: '2026-06-19' },
  '22301': { medianSalePrice: 1122500, medianDaysOnMarket: 28, activeListings: 30, percentAboveList: 0.3077, updatedAt: '2026-06-19' },
  '22302': { medianSalePrice: 400000, medianDaysOnMarket: 33, activeListings: 69, percentAboveList: 0.3684, updatedAt: '2026-06-19' },
  '22303': { medianSalePrice: 519000, medianDaysOnMarket: 38, activeListings: 44, percentAboveList: 0.3051, updatedAt: '2026-06-19' },
  '22304': { medianSalePrice: 525000, medianDaysOnMarket: 40, activeListings: 161, percentAboveList: 0.2318, updatedAt: '2026-06-19' },
  '22305': { medianSalePrice: 855000, medianDaysOnMarket: 36, activeListings: 18, percentAboveList: 0.4545, updatedAt: '2026-06-19' },
  '22306': { medianSalePrice: 735000, medianDaysOnMarket: 27, activeListings: 58, percentAboveList: 0.5079, updatedAt: '2026-06-19' },
  '22307': { medianSalePrice: 730000, medianDaysOnMarket: 33, activeListings: 35, percentAboveList: 0.3836, updatedAt: '2026-06-19' },
  '22308': { medianSalePrice: 1021000, medianDaysOnMarket: 28, activeListings: 38, percentAboveList: 0.3889, updatedAt: '2026-06-19' },
  '22309': { medianSalePrice: 670000, medianDaysOnMarket: 34, activeListings: 86, percentAboveList: 0.3945, updatedAt: '2026-06-19' },
  '22310': { medianSalePrice: 680000, medianDaysOnMarket: 25, activeListings: 60, percentAboveList: 0.5357, updatedAt: '2026-06-19' },
  '22311': { medianSalePrice: 715000, medianDaysOnMarket: 21, activeListings: 16, percentAboveList: 0.4828, updatedAt: '2026-06-19' },
  '22312': { medianSalePrice: 638750, medianDaysOnMarket: 39, activeListings: 70, percentAboveList: 0.3378, updatedAt: '2026-06-19' },
  '22314': { medianSalePrice: 905000, medianDaysOnMarket: 27, activeListings: 157, percentAboveList: 0.4152, updatedAt: '2026-06-19' },
  '22315': { medianSalePrice: 724950, medianDaysOnMarket: 24, activeListings: 51, percentAboveList: 0.4819, updatedAt: '2026-06-19' },
}

const CANDEE_ZIPS = Object.keys(MARKET_DATA)

export async function GET(request: NextRequest) {
  const zip = request.nextUrl.searchParams.get('zip')

  if (zip) {
    if (!CANDEE_ZIPS.includes(zip)) {
      return NextResponse.json({ error: 'ZIP not in service area' }, { status: 400 })
    }
    return NextResponse.json({ zip, ...MARKET_DATA[zip] })
  }

  const summary = Object.fromEntries(
    CANDEE_ZIPS.map(z => [z, { zip: z, ...MARKET_DATA[z] }])
  )
  return NextResponse.json({ zips: summary, updatedAt: '2026-06-19' })
}
