import { NextRequest, NextResponse } from 'next/server'

// Auto-generated by scripts/update-market-data.mjs
// Source: Redfin Public Market Data (county_market_tracker) mapped to ZIP codes
// Last updated: 2026-04-06
const MARKET_DATA: Record<string, {
  medianSalePrice: number
  medianDaysOnMarket: number
  activeListings: number | null
  percentAboveList: number
  updatedAt: string
}> = {
  '22041': { medianSalePrice: 723000, medianDaysOnMarket: 33, activeListings: 1420, percentAboveList: 0.4201, updatedAt: '2026-04-06' },
  '22042': { medianSalePrice: 723000, medianDaysOnMarket: 33, activeListings: 1420, percentAboveList: 0.4201, updatedAt: '2026-04-06' },
  '22043': { medianSalePrice: 723000, medianDaysOnMarket: 33, activeListings: 1420, percentAboveList: 0.4201, updatedAt: '2026-04-06' },
  '22044': { medianSalePrice: 723000, medianDaysOnMarket: 33, activeListings: 1420, percentAboveList: 0.4201, updatedAt: '2026-04-06' },
  '22101': { medianSalePrice: 723000, medianDaysOnMarket: 33, activeListings: 1420, percentAboveList: 0.4201, updatedAt: '2026-04-06' },
  '22102': { medianSalePrice: 723000, medianDaysOnMarket: 33, activeListings: 1420, percentAboveList: 0.4201, updatedAt: '2026-04-06' },
  '22201': { medianSalePrice: 437500, medianDaysOnMarket: 46, activeListings: 218, percentAboveList: 0.1692, updatedAt: '2026-04-06' },
  '22202': { medianSalePrice: 437500, medianDaysOnMarket: 46, activeListings: 218, percentAboveList: 0.1692, updatedAt: '2026-04-06' },
  '22203': { medianSalePrice: 437500, medianDaysOnMarket: 46, activeListings: 218, percentAboveList: 0.1692, updatedAt: '2026-04-06' },
  '22204': { medianSalePrice: 437500, medianDaysOnMarket: 46, activeListings: 218, percentAboveList: 0.1692, updatedAt: '2026-04-06' },
  '22205': { medianSalePrice: 437500, medianDaysOnMarket: 46, activeListings: 218, percentAboveList: 0.1692, updatedAt: '2026-04-06' },
  '22206': { medianSalePrice: 437500, medianDaysOnMarket: 46, activeListings: 218, percentAboveList: 0.1692, updatedAt: '2026-04-06' },
  '22207': { medianSalePrice: 437500, medianDaysOnMarket: 46, activeListings: 218, percentAboveList: 0.1692, updatedAt: '2026-04-06' },
  '22209': { medianSalePrice: 437500, medianDaysOnMarket: 46, activeListings: 218, percentAboveList: 0.1692, updatedAt: '2026-04-06' },
  '22213': { medianSalePrice: 437500, medianDaysOnMarket: 46, activeListings: 218, percentAboveList: 0.1692, updatedAt: '2026-04-06' },
}

const CANDEE_ZIPS = Object.keys(MARKET_DATA)

export async function GET(request: NextRequest) {
  const zip = request.nextUrl.searchParams.get('zip')

  if (zip) {
    if (!CANDEE_ZIPS.includes(zip)) {
      return NextResponse.json({ error: 'ZIP not in service area' }, { status: 400 })
    }
    return NextResponse.json({ zip, ...MARKET_DATA[zip] })
  }

  const summary = Object.fromEntries(
    CANDEE_ZIPS.map(z => [z, { zip: z, ...MARKET_DATA[z] }])
  )
  return NextResponse.json({ zips: summary, updatedAt: '2026-04-06' })
}
