import { NextRequest, NextResponse } from 'next/server'

// Auto-generated by scripts/update-market-data.mjs
// Source: Redfin Public Market Data (zip_code_market_tracker) — ZIP-level accuracy
// Last updated: 2026-04-13
const MARKET_DATA: Record<string, {
  medianSalePrice: number
  medianDaysOnMarket: number
  activeListings: number | null
  percentAboveList: number
  updatedAt: string
}> = {
  '20190': { medianSalePrice: 536450, medianDaysOnMarket: 42, activeListings: 50, percentAboveList: 0.2632, updatedAt: '2026-04-13' },
  '22041': { medianSalePrice: 377500, medianDaysOnMarket: 47, activeListings: 37, percentAboveList: 0.1458, updatedAt: '2026-04-13' },
  '22042': { medianSalePrice: 743999, medianDaysOnMarket: 50, activeListings: 50, percentAboveList: 0.2667, updatedAt: '2026-04-13' },
  '22043': { medianSalePrice: 870000, medianDaysOnMarket: 43, activeListings: 37, percentAboveList: 0.2979, updatedAt: '2026-04-13' },
  '22044': { medianSalePrice: 868790, medianDaysOnMarket: 41, activeListings: 15, percentAboveList: 0.3, updatedAt: '2026-04-13' },
  '22046': { medianSalePrice: 998500, medianDaysOnMarket: 42, activeListings: 39, percentAboveList: 0.225, updatedAt: '2026-04-13' },
  '22066': { medianSalePrice: 1638551, medianDaysOnMarket: 92, activeListings: 34, percentAboveList: 0.375, updatedAt: '2026-04-13' },
  '22101': { medianSalePrice: 1778950, medianDaysOnMarket: 69, activeListings: 78, percentAboveList: 0.2813, updatedAt: '2026-04-13' },
  '22102': { medianSalePrice: 740000, medianDaysOnMarket: 64, activeListings: 72, percentAboveList: 0.1392, updatedAt: '2026-04-13' },
  '22180': { medianSalePrice: 990000, medianDaysOnMarket: 48, activeListings: 38, percentAboveList: 0.375, updatedAt: '2026-04-13' },
  '22201': { medianSalePrice: 725000, medianDaysOnMarket: 61, activeListings: 74, percentAboveList: 0.1646, updatedAt: '2026-04-13' },
  '22202': { medianSalePrice: 625000, medianDaysOnMarket: 68, activeListings: 38, percentAboveList: 0, updatedAt: '2026-04-13' },
  '22203': { medianSalePrice: 625000, medianDaysOnMarket: 69, activeListings: 33, percentAboveList: 0.1915, updatedAt: '2026-04-13' },
  '22204': { medianSalePrice: 659250, medianDaysOnMarket: 61, activeListings: 73, percentAboveList: 0.2, updatedAt: '2026-04-13' },
  '22205': { medianSalePrice: 1062500, medianDaysOnMarket: 35, activeListings: 18, percentAboveList: 0.4688, updatedAt: '2026-04-13' },
  '22206': { medianSalePrice: 540000, medianDaysOnMarket: 39, activeListings: 37, percentAboveList: 0.3, updatedAt: '2026-04-13' },
  '22207': { medianSalePrice: 1275000, medianDaysOnMarket: 74, activeListings: 52, percentAboveList: 0.197, updatedAt: '2026-04-13' },
  '22209': { medianSalePrice: 515000, medianDaysOnMarket: 60, activeListings: 59, percentAboveList: 0.1053, updatedAt: '2026-04-13' },
  '22213': { medianSalePrice: 653000, medianDaysOnMarket: 31, activeListings: 7, percentAboveList: 0.7143, updatedAt: '2026-04-13' },
  '22301': { medianSalePrice: 990000, medianDaysOnMarket: 30, activeListings: 28, percentAboveList: 0.3182, updatedAt: '2026-04-13' },
  '22302': { medianSalePrice: 349950, medianDaysOnMarket: 59, activeListings: 51, percentAboveList: 0.22, updatedAt: '2026-04-13' },
  '22303': { medianSalePrice: 500000, medianDaysOnMarket: 48, activeListings: 42, percentAboveList: 0.129, updatedAt: '2026-04-13' },
  '22304': { medianSalePrice: 385000, medianDaysOnMarket: 53, activeListings: 107, percentAboveList: 0.1705, updatedAt: '2026-04-13' },
  '22305': { medianSalePrice: 727500, medianDaysOnMarket: 36, activeListings: 13, percentAboveList: 0.3214, updatedAt: '2026-04-13' },
  '22306': { medianSalePrice: 640500, medianDaysOnMarket: 59, activeListings: 40, percentAboveList: 0.2128, updatedAt: '2026-04-13' },
  '22307': { medianSalePrice: 850000, medianDaysOnMarket: 49, activeListings: 30, percentAboveList: 0.2766, updatedAt: '2026-04-13' },
  '22308': { medianSalePrice: 1020000, medianDaysOnMarket: 52, activeListings: 18, percentAboveList: 0.2308, updatedAt: '2026-04-13' },
  '22309': { medianSalePrice: 589900, medianDaysOnMarket: 61, activeListings: 59, percentAboveList: 0.2464, updatedAt: '2026-04-13' },
  '22310': { medianSalePrice: 660000, medianDaysOnMarket: 51, activeListings: 26, percentAboveList: 0.3684, updatedAt: '2026-04-13' },
  '22311': { medianSalePrice: 508250, medianDaysOnMarket: 35, activeListings: 9, percentAboveList: 0.3125, updatedAt: '2026-04-13' },
  '22312': { medianSalePrice: 634500, medianDaysOnMarket: 46, activeListings: 41, percentAboveList: 0.3043, updatedAt: '2026-04-13' },
  '22314': { medianSalePrice: 890000, medianDaysOnMarket: 56, activeListings: 113, percentAboveList: 0.233, updatedAt: '2026-04-13' },
  '22315': { medianSalePrice: 715000, medianDaysOnMarket: 45, activeListings: 22, percentAboveList: 0.2174, updatedAt: '2026-04-13' },
}

const CANDEE_ZIPS = Object.keys(MARKET_DATA)

export async function GET(request: NextRequest) {
  const zip = request.nextUrl.searchParams.get('zip')

  if (zip) {
    if (!CANDEE_ZIPS.includes(zip)) {
      return NextResponse.json({ error: 'ZIP not in service area' }, { status: 400 })
    }
    return NextResponse.json({ zip, ...MARKET_DATA[zip] })
  }

  const summary = Object.fromEntries(
    CANDEE_ZIPS.map(z => [z, { zip: z, ...MARKET_DATA[z] }])
  )
  return NextResponse.json({ zips: summary, updatedAt: '2026-04-13' })
}
